---
version: "3.7"
# ---------------------------------------------------------------------
# | NodeJS Service                                                    |
# ---------------------------------------------------------------------

services:
  node_farm:
    build:
      context: ../backend/node_farm
      dockerfile: node_farm.Dockerfile
    image: paulserbandev/node_farm
    container_name: node_farm-compose
    restart: always
    volumes:
      - ../backend/node_farm:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
